version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/images/ubuntu"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(docker)"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
