name: Build and Push Container Image

description: Build a container image and push to GitHub Packages using Podman

inputs:
  image-name:
    description: 'Name of the image'
    required: true
  image-tag:
    description: 'Tag for the container image'
    required: false
    default: 'latest'
  dockerfile:
    description: 'Path to Dockerfile'
    required: false
    default: './Dockerfile'
  context:
    description: 'Build context'
    required: false
    default: '.'
  github-token:
    description: 'GitHub Token for registry login'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Podman
      uses: redhat-actions/podman-login@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}

    - name: Build image with Podman
      run: |
        REPO_LC="${GITHUB_REPOSITORY,,}"
        podman build -f ${{ inputs.dockerfile }} -t ghcr.io/${REPO_LC}/${{ inputs.image-name }}:${{ inputs.image-tag }} ${{ inputs.context }}
      shell: bash

    - name: Push image with Podman
      if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
      run: |
        REPO_LC="${GITHUB_REPOSITORY,,}"
        podman push ghcr.io/${REPO_LC}/${{ inputs.image-name }}:${{ inputs.image-tag }}
      shell: bash