name: Test Build and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [published]

jobs:
  build-container:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
    strategy:
      matrix:
        include:
          - image-name: ubuntu
            dockerfile: images/ubuntu/Dockerfile
            context: images/ubuntu
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry (podman)
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin


      - name: Build ${{ matrix.image-name }} Container
        uses: ./.github/actions/container-build
        with:
          image-name: ${{ matrix.image-name }}
          dockerfile: ${{ matrix.dockerfile }}
          context: ${{ matrix.context }}
          github-token: ${{ secrets.GITHUB_TOKEN }}